name: optoview_flutter
description: A neuro-optometry app built with Flutter.
publish_to: 'none'

# Versión de la app:
# 1.0.0 → versión visible
# +1    → número de compilación
version: 3.3.0-beta.1+6

environment:
  sdk: '^3.8.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.20.2
  package_info_plus: ^8.3.1
  shared_preferences: ^2.3.0
  pdf: ^3.11.0
  printing: ^5.13.0
  excel: ^4.0.0
  share_plus: ^10.0.0
  file_picker: ^8.0.0
  path_provider: ^2.1.0
  animations: ^2.0.11
  uuid: ^4.4.0
  archive: ^3.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#0A1929"
  adaptive_icon_foreground: "assets/images/logo.png"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/logo.png
    - assets/images/test_peripheral.png
    - assets/images/location_peripheal.png
    - assets/images/macdonald_chart.png
